language: objective-c
before_install:
- brew update
- brew upgrade xctool
- brew install s3cmd
- gem install cocoapods --no-ri --no-rdoc
script:
- xcodebuild -workspace Titanium.xcworkspace -scheme Titanium -sdk iphonesimulator test
